#GNUPlot script for plotting filesize againtst query number
#
# Call from an interactive session like...
# call "query-file-size.gnu" <input file>
# <input file> should the smt2-files-sizes.log" file generated by KLEE

set mouse 

#use log scale for file size
set log y

set xlabel "Query number"
set ylabel "Query file size (MB)"

plot "$0" using 1:(column(2)/1000000) with line


